// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import EditableController from "controllers/editable_controller"
application.register("editable", EditableController)

import SortableController from "controllers/sortable_controller"
application.register("sortable", SortableController)
