// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application";

import EditableController from "controllers/editable_controller";
application.register("editable", EditableController);

import NavbarController from "controllers/navbar_controller";
application.register("navbar", NavbarController);

import NotificationController from "controllers/notification_controller";
application.register("notification", NotificationController);

import SortableController from "controllers/sortable_controller";
application.register("sortable", SortableController);
